#!/usr/bin/env bash

cat <<EOT | sudo tee /etc/systemd/system/alive_boi.service > /dev/null
[Unit]
Description=Alive Boi

[Service]
Type=simple
Restart=on-failure
RestartSec=5s
ExecStart=/home/$(whoami)/.cargo/bin/alive_boi --mqtt_host mqtt.local --device_name $(hostname) --topic devices

[Install]
WantedBy=default.target
EOT

sudo systemctl daemon-reload
sudo systemctl enable alive_boi
sudo systemctl start alive_boi
